CONFIG = {};

//API STATUS
CONFIG.STATUS_CODE_OK = 200;
CONFIG.STATUS_CODE_SESSION_EXP = 440;
CONFIG.STATUS_CODE_UNAUTHORIZED = 401;
CONFIG.STATUS_CODE_API_NOT_FOUND = 414;
CONFIG.STATUS_CODE_NOT_FOUND = 404;
CONFIG.STATUS_CODE_FOUND = 302;
CONFIG.STATUS_CODE_BAD_REQUEST = 400;
CONFIG.STATUS_CODE_INTERNAL_SERVER = 500;
CONFIG.ERROR_CODE = 422;



CONFIG.INACTIVE_RECORD = 0;
CONFIG.ACTIVE_RECORD = 1;


// missing messages 

CONFIG.ERR_INTERNAL_SERVER_ERROR = 'Internal server error'
CONFIG.ERROR_MISSING_USER_NAME = 'Please provide username';
CONFIG.ERROR_MISSING_EMAIL = 'Please provide email';
CONFIG.ERROR_MISSING_PASSWORD = 'Please provide password';
CONFIG.ERROR_MISSING_FIRST_NAME = 'Please provide firstName';
CONFIG.ERROR_MISSING_LAST_NAME = 'Please provide lastName';
CONFIG.ERROR_MISSING_USER_ID = 'Please provide user Id';


// user types 

CONFIG.USER_TYPE_USER = 1;
CONFIG.USER_TYP_ADMIN = 2;



CONFIG.MESS_INTERNAL_SERVER_ERROR = 'Internal server error !'